import 'package:flutter/cupertino.dart';

import '../model/menumodel.dart';
import '../model/restaurantsmodel.dart';

class RestaurantListViewModel with ChangeNotifier {
  final List<Restaurant> restaurants = [
    Restaurant(
      id: '1',
      name: 'Khana Khazana',
      menu: [
        MenuItem(
          name: 'Chicken Jalfrezi',
          description:
              'Tender pieces of chicken cooked with bell peppers, onions, tomatoes, and a blend of spices, resulting in a colorful and flavorful dish.',
          imageUrl: 'assets/images/restaurantsone/chicken_jalfrezi.jpg',
          calories: 300,
          price: 12.99,
          fat: 15,
          protein: 25,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
          sodium: 700,
        ),
        MenuItem(
          name: 'Chicken Biryani',
          description:
              'A fragrant rice dish cooked with marinated chicken, aromatic spices, and herbs.',
          imageUrl: 'assets/images/restaurantsone/Chicken_Biryani.jpg',
          calories: 400,
          fat: 15,
          protein: 20,
          sodium: 800,
          price: 14.99,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
        ),
        MenuItem(
          name: 'Seekh Kebab',
          description:
              'Minced meat mixed with spices, shaped into skewers, and grilled.',
          imageUrl: 'assets/images/restaurantsone/chapli_kabab.jpg',
          calories: 200,
          price: 9.99,
          fat: 12,
          protein: 18,
          sodium: 300,
          category: 'Appetizers',
          allergens: ['Gluten', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
        ),
        MenuItem(
          name: 'Nihari',
          description:
              'A slow-cooked stew made with tender beef or lamb, flavored with spices and served with naan.',
          imageUrl: 'assets/images/restaurantsone/Nihari.jpg',
          calories: 300,
          price: 13.99,
          fat: 20,
          protein: 25,
          sodium: 700,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Beef', 'Wheat', 'Sulfites'],
        ),
        MenuItem(
          name: 'Haleem',
          description:
              'A thick, savory porridge made with wheat, barley, lentils, and meat, slow-cooked with spices.',
          imageUrl: 'assets/images/restaurantsone/haleem.jpg',
          calories: 350,
          price: 11.99,
          fat: 10,
          protein: 15,
          sodium: 600,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Beef', 'Wheat', 'Barley'],
        ),
        MenuItem(
          name: 'Aloo Palak',
          description:
              'A vegetarian dish made with potatoes and spinach cooked together with spices.',
          imageUrl: 'assets/images/restaurantsone/aloo palak.jpg',
          calories: 200,
          price: 8.99,
          fat: 10,
          protein: 5,
          sodium: 400,
          category: 'Vegetarian',
          allergens: [],
        ),
        MenuItem(
          name: 'Chicken Karahi',
          description:
              'Tender chicken cooked in a tomato-based gravy with spices, served with naan or rice.',
          imageUrl: 'assets/images/restaurantsone/chicken_karhai.jpg',
          calories: 300,
          price: 12.99,
          fat: 15,
          protein: 25,
          sodium: 700,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
        ),
        MenuItem(
          name: 'Sindhi Biryani',
          description:
              'A spicy rice dish cooked with marinated meat, potatoes, and various spices.',
          imageUrl: 'assets/images/restaurantsone/sindhi_biryani.jpg',
          calories: 450,
          price: 15.99,
          fat: 20,
          protein: 25,
          sodium: 900,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Beef', 'Wheat', 'Sulfites'],
        ),
        MenuItem(
          name: 'Daal Chawal',
          description: 'Lentils cooked with spices, served with steamed rice.',
          imageUrl: 'assets/images/restauranttwo/daal_chawal.jpg',
          calories: 250,
          price: 7.99,
          fat: 5,
          protein: 10,
          sodium: 500,
          category: 'Vegetarian',
          allergens: [],
        ),
        MenuItem(
          name: 'Saag Gosht',
          description: 'Tender mutton or beef cooked with spinach and spices.',
          imageUrl: 'assets/images/restaurantsone/saag_gosht.jpg',
          calories: 350,
          price: 14.99,
          fat: 15,
          protein: 20,
          sodium: 600,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Mutton', 'Wheat', 'Sulfites'],
        ),
        MenuItem(
          name: 'Chicken Tikka',
          description:
              'Marinated chicken pieces skewered and grilled, served with mint chutney.',
          imageUrl: 'assets/images/restaurantsone/chicken_tikka.jpg',
          calories: 250,
          price: 10.99,
          fat: 10,
          protein: 20,
          sodium: 400,
          category: 'Appetizers',
          allergens: ['Gluten', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
        ),
        MenuItem(
          name: 'Mutton Korma',
          description:
              'Tender mutton cooked in a rich, creamy gravy with yogurt and spices.',
          imageUrl: 'assets/images/restaurantsone/mutton_korma.jpg',
          calories: 400,
          price: 15.99,
          fat: 25,
          protein: 20,
          sodium: 800,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Mutton', 'Nuts', 'Sulfites'],
        ),
        MenuItem(
          name: 'Chicken Handi',
          description:
              'Chicken cooked in a thick, creamy sauce, served in a traditional clay pot.',
          imageUrl: 'assets/images/restauranttwo/chicken_handi.jpg',
          calories: 350,
          price: 12.99,
          fat: 15,
          protein: 25,
          sodium: 700,
          category: 'Main Dishes',
          allergens: ['Gluten', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
        ),
        MenuItem(
          name: 'Palak Paneer',
          description: 'Paneer cubes cooked in a creamy spinach gravy.',
          imageUrl: 'assets/images/restaurantsone/palak_paneer.jpg',
          calories: 300,
          price: 11.99,
          fat: 20,
          protein: 15,
          sodium: 700,
          category: 'Vegetarian',
          allergens: ['Dairy', 'Soy', 'Wheat', 'Eggs', 'Sulfites'],
        ),
        MenuItem(
          name: 'Gulab Jamun',
          description:
              'Soft dumplings made from milk solids soaked in sugar syrup.',
          imageUrl: 'assets/images/restaurantsone/gulab_jamun.jpg',
          calories: 250,
          price: 4.99,
          fat: 12,
          protein: 4,
          sodium: 30,
          category: 'Desserts',
          allergens: ['Milk', 'Tree nuts', 'Wheat', 'Soy', 'Sulfites'],
        ),
        MenuItem(
          name: 'Jalebi',
          description: 'Crisp spiral-shaped batter soaked in sugar syrup.',
          imageUrl: 'assets/images/restaurantsone/jalebi.jpg',
          calories: 200,
          price: 3.99,
          fat: 10,
          protein: 2,
          sodium: 25,
          category: 'Desserts',
          allergens: ['Wheat', 'Tree nuts', 'Milk', 'Eggs', 'Sesame'],
        ),
        MenuItem(
          name: 'Ras Malai',
          description:
              'Soft cheese patties soaked in sweetened thickened milk.',
          imageUrl: 'assets/images/restaurantsone/ras_malai.jpg',
          calories: 300,
          price: 5.99,
          fat: 20,
          protein: 10,
          sodium: 25,
          category: 'Desserts',
          allergens: ['Milk', 'Tree nuts', 'Wheat', 'Soy', 'Cardamom'],
        ),
        // Add more MenuItems as needed
      ],
    ),
    Restaurant(
      id: '2',
      name: 'Pakistani Kitchen',
      menu: [
        MenuItem(
          name: 'Beef Biryani',
          description:
              'Aromatic rice with tender beef pieces, spices, and herbs, cooked to perfection.',
          imageUrl: 'assets/images/restauranttwo/chicken_biryani.jpg',
          calories: 450,
          protein: 20,
          fat: 10,
          sodium: 800,
          price: 14.99,
          category: 'Main Course',
          allergens: [],
        ),
        MenuItem(
          name: 'Tandoori Delight (Chicken Biryani)',
          description:
              'Marinate chicken in spices & yogurt, cook basmati rice & layer with chicken & spices.',
          imageUrl: 'assets/images/restauranttwo/chicken_biryani.jpg',
          calories: 400,
          protein: 18,
          fat: 8,
          sodium: 750,
          price: 12.99,
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Slow-Cooked Stew (Nihari)',
          description:
              'Marinate meat (beef/lamb) in spices & yogurt, slow-cooked with bone marrow.',
          calories: 500,
          protein: 25,
          fat: 15,
          sodium: 850,
          price: 16.99,
          imageUrl: 'assets/images/restauranttwo/nihari (2).jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Spicy Chicken Fusion (Chicken Karahi)',
          description:
              'Marinate chicken in spices & yogurt, cooked with tomatoes and spices.',
          calories: 350,
          protein: 22,
          fat: 10,
          sodium: 700,
          price: 13.99,
          imageUrl: 'assets/images/restauranttwo/chicken_karhai.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Spinach Potato Delight (Aloo Palak)',
          description:
              'Boil potatoes & spinach, blend with garlic, ginger & spices.',
          calories: 200,
          protein: 5,
          fat: 6,
          sodium: 400,
          price: 10.99,
          imageUrl: 'assets/images/restauranttwo/aloo_palak.jpg',
          category: 'Main Course',
          allergens: [],
        ),
        MenuItem(
          name: 'Hearty Stew (Haleem)',
          description:
              'Mix wheat, barley, lentils & meat, cooked slowly with spices.',
          calories: 400,
          protein: 20,
          fat: 12,
          sodium: 750,
          price: 14.99,
          imageUrl: 'assets/images/restauranttwo/haleem (1).jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Sindhi Spice Rice (Sindhi Biryani)',
          description:
              'Marinate meat in spices & yogurt, cooked with basmati rice.',
          calories: 450,
          protein: 22,
          fat: 10,
          sodium: 800,
          price: 15.99,
          imageUrl: 'assets/images/restauranttwo/sindhi_biryani.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Lentil Rice Bowl (Daal Chawal)',
          description: 'Boil lentils & rice, add spices & ghee.',
          calories: 300,
          protein: 10,
          fat: 8,
          sodium: 600,
          price: 9.99,
          imageUrl: 'assets/images/restauranttwo/daal_chawal.jpg',
          category: 'Main Course',
          allergens: [],
        ),
        MenuItem(
          name: 'Spinach Meat Curry (Saag Gosht)',
          description: 'Cook meat in spinach gravy with spices.',
          calories: 400,
          protein: 25,
          fat: 12,
          sodium: 750,
          price: 14.99,
          imageUrl: 'assets/images/restauranttwo/saag_gosht.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Mutton Korma Delight',
          description:
              'Marinate meat in yogurt & spices, cooked in creamy gravy.',
          calories: 500,
          protein: 22,
          fat: 20,
          sodium: 850,
          price: 17.99,
          imageUrl: 'assets/images/restauranttwo/mutton_korma.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites', 'Tree Nuts'],
        ),
        MenuItem(
          name: 'Veggie Rice Medley (Veg Pulao)',
          description: 'Cook mixed veggies & basmati rice with spices.',
          calories: 250,
          protein: 6,
          fat: 5,
          sodium: 500,
          price: 10.99,
          imageUrl: 'assets/images/restauranttwo/veg_pulao.jpg',
          category: 'Main Course',
          allergens: [],
        ),
        MenuItem(
          name: 'Clay Pot Chicken',
          description:
              'Marinate chicken in spices & yogurt, cooked in clay pot.',
          calories: 350,
          protein: 20,
          fat: 10,
          sodium: 700,
          price: 13.99,
          imageUrl: 'assets/images/restauranttwo/chicken_handi.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Meat Potato Curry (Aloo Gosht)',
          description:
              'Cook meat & potatoes in spicy gravy with garlic & ginger.',
          calories: 400,
          protein: 22,
          fat: 12,
          sodium: 750,
          price: 14.99,
          imageUrl: 'assets/images/restauranttwo/aloo_gosht.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Meatball Curry (Nargisi Kofta)',
          description: 'Mix meat with spices & eggs, cooked in gravy.',
          imageUrl: 'assets/images/restauranttwo/nargisi_kofta.jpg',
          calories: 400,
          protein: 22,
          fat: 12,
          sodium: 750,
          price: 15.99,
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites', 'Eggs'],
        ),
        MenuItem(
          name: 'Gulab Jamun',
          description: 'Deep fried milk dough balls soaked in rose syrup.',
          calories: 300,
          protein: 5,
          fat: 10,
          sodium: 150,
          price: 5.99,
          imageUrl: 'assets/images/restauranttwo/gulab_jamun.jpg',
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Jalebi',
          description: 'Deep fried fermented batter soaked in sugar syrup.',
          calories: 300,
          protein: 3,
          fat: 12,
          sodium: 100,
          price: 4.99,
          imageUrl: 'assets/images/restauranttwo/jalebi (1).jpg',
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Ras Malai',
          description:
              'Paneer soaked in cream & sugar, flavored with cardamom.',
          calories: 350,
          protein: 8,
          fat: 15,
          sodium: 200,
          price: 6.99,
          imageUrl: 'assets/images/restauranttwo/ras_malai.jpg',
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Sohan Halwa',
          description: 'Wheat flour & ghee, flavored with nuts & cardamom.',
          calories: 300,
          protein: 5,
          fat: 12,
          sodium: 150,
          price: 5.99,
          imageUrl: 'assets/images/restauranttwo/sohan_halwa.jpg',
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Gajar Ka Halwa',
          description: 'Grated carrots cooked in milk, flavored with cardamom.',
          calories: 250,
          protein: 5,
          fat: 10,
          sodium: 150,
          price: 5.99,
          imageUrl: 'assets/images/restauranttwo/gajar_ka_halwa.jpg',
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Sheer Khurma',
          description: 'Vermicelli cooked in milk with sugar & cardamom.',
          calories: 300,
          protein: 6,
          fat: 12,
          sodium: 150,
          price: 5.99,
          imageUrl: 'assets/images/restauranttwo/sheer_khurma.jpg',
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Fresh Limeade',
          description: 'Classic summer drink with a sweet and tangy twist.',
          calories: 50,
          protein: 0,
          fat: 0,
          sodium: 10,
          price: 3.99,
          imageUrl: 'assets/images/restauranttwo/fresh_lemonade.jpg',
          category: 'Beverage',
          allergens: [],
        ),
        MenuItem(
          name: 'Chai (Milk Tea)',
          description: 'Traditional spiced tea with milk and sugar.',
          calories: 150,
          protein: 4,
          fat: 6,
          sodium: 50,
          price: 2.99,
          imageUrl: 'assets/images/restauranttwo/iced_lemon_tea.jpg',
          category: 'Beverage',
          allergens: ['Milk'],
        ),
        MenuItem(
          name: 'Mint Margarita',
          description: 'Refreshing drink with mint and lemon.',
          calories: 70,
          protein: 0,
          fat: 0,
          sodium: 15,
          price: 4.99,
          imageUrl: 'assets/images/restauranttwo/cocumber_mint_refresher.jpg',
          category: 'Beverage',
          allergens: [],
        ),
      ],
    ),
    Restaurant(
      id: '3',
      name: 'Spice Oasis',
      menu: [
        MenuItem(
          name: 'Paneer Tikka',
          description:
              'Grilled paneer chunks marinated in yogurt and spices, served with mint chutney.',
          imageUrl: 'assets/images/restauranttwo/paneer_ikka.jpg',
          calories: 250,
          price: 10.99,
          fat: 10,
          protein: 20,
          sodium: 400,
          category: 'Appetizer',
          allergens: ['Dairy'],
        ),
        MenuItem(
          name: 'Cucumber Mint Refresher',
          description: 'Light and refreshing, perfect for hot days.',
          calories: 90,
          protein: 0,
          fat: 0,
          sodium: 20,
          price: 2.49,
          imageUrl: 'assets/images/restauranttwo/cocumber_mint_refresher.jpg',
          category: 'Beverage',
          allergens: [],
        ),
        MenuItem(
          name: 'Samosas',
          description:
              'Fried pastry pockets filled with spiced potatoes and peas.',
          calories: 200,
          price: 5.99,
          fat: 19,
          protein: 18,
          sodium: 8,
          imageUrl: 'assets/images/restauranttwo/samosas.jpg',
          category: 'Appetizer',
          allergens: ['Gluten'],
        ),
        MenuItem(
          name: 'Tandoori Delight (Chicken Biryani)',
          description:
              'Marinate chicken in spices & yogurt, cook basmati rice & layer with chicken & spices.',
          imageUrl: 'assets/images/restauranttwo/chicken_biryani.jpg',
          calories: 400,
          protein: 18,
          fat: 8,
          sodium: 750,
          price: 12.99,
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Gulab Jamun',
          imageUrl: 'assets/images/restauranttwo/gulab_jamun.jpg',
          description: 'Deep fried milk dough balls soaked in rose syrup.',
          calories: 300,
          protein: 5,
          fat: 10,
          sodium: 150,
          price: 5.99,
          category: 'Dessert',
          allergens: [],
        ),
        MenuItem(
          name: 'Spicy Chicken Fusion (Chicken Karahi)',
          description: 'Marinated chicken cooked with tomatoes and spices.',
          calories: 350,
          price: 13.99,
          protein: 22,
          fat: 10,
          sodium: 700,
          imageUrl: 'assets/images/restauranttwo/chicken_karhai.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Fresh Fruit Smoothie',
          description: 'Blended fruity goodness with strawberries and bananas.',
          calories: 200,
          price: 3.99,
          protein: 2,
          fat: 1,
          sodium: 40,
          imageUrl: 'assets/images/restauranttwo/fresh_fruit_smoothie.jpg',
          category: 'Beverage',
          allergens: [],
        ),
        MenuItem(
          name: 'Hearty Stew (Haleem)',
          description:
              'Mix of wheat, barley, lentils & meat, slow-cooked with spices.',
          calories: 400,
          price: 14.99,
          protein: 20,
          fat: 12,
          sodium: 750,
          imageUrl: 'assets/images/restauranttwo/haleem (1).jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites'],
        ),
        MenuItem(
          name: 'Mutton Korma Delight',
          description: 'Marinated mutton cooked in creamy gravy with nuts.',
          calories: 500,
          protein: 22,
          fat: 20,
          sodium: 850,
          price: 17.99,
          imageUrl: 'assets/images/restauranttwo/mutton_korma.jpg',
          category: 'Main Course',
          allergens: ['Gluten', 'Sulphites', 'Tree Nuts'],
        ),
        // Add more MenuItems
      ],
    )
  ];
}
